//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace Pinble_Challenge.localhost {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ChallSerSoap", Namespace="http://tempuri.org/")]
    public partial class ChallSer : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback addChallOperationCompleted;
        
        private System.Threading.SendOrPostCallback logionUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback uloginOperationCompleted;
        
        private System.Threading.SendOrPostCallback perTableSOperationCompleted;
        
        private System.Threading.SendOrPostCallback perTableDOperationCompleted;
        
        private System.Threading.SendOrPostCallback perTablePOperationCompleted;
        
        private System.Threading.SendOrPostCallback TabCompOFSOperationCompleted;
        
        private System.Threading.SendOrPostCallback TabCompOFS_DOperationCompleted;
        
        private System.Threading.SendOrPostCallback TabCompOFS_POperationCompleted;
        
        private System.Threading.SendOrPostCallback perRankDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback perRankData_DOperationCompleted;
        
        private System.Threading.SendOrPostCallback perRankData_POperationCompleted;
        
        private System.Threading.SendOrPostCallback IntegralTableOperationCompleted;
        
        private System.Threading.SendOrPostCallback IntegralTable_dOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserAchienementOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserAchienement_dOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserAchienement_pOperationCompleted;
        
        private System.Threading.SendOrPostCallback LottConOperationCompleted;
        
        private System.Threading.SendOrPostCallback PeriodOperationCompleted;
        
        private System.Threading.SendOrPostCallback AllowOperationCompleted;
        
        private System.Threading.SendOrPostCallback AllowTimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback FlipOperationCompleted;
        
        private System.Threading.SendOrPostCallback URLDecodeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ChallSer() {
            this.Url = global::Pinble_Challenge.Properties.Settings.Default.Pinble_Challenge_localhost_ChallSer;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event addChallCompletedEventHandler addChallCompleted;
        
        /// <remarks/>
        public event logionUserCompletedEventHandler logionUserCompleted;
        
        /// <remarks/>
        public event uloginCompletedEventHandler uloginCompleted;
        
        /// <remarks/>
        public event perTableSCompletedEventHandler perTableSCompleted;
        
        /// <remarks/>
        public event perTableDCompletedEventHandler perTableDCompleted;
        
        /// <remarks/>
        public event perTablePCompletedEventHandler perTablePCompleted;
        
        /// <remarks/>
        public event TabCompOFSCompletedEventHandler TabCompOFSCompleted;
        
        /// <remarks/>
        public event TabCompOFS_DCompletedEventHandler TabCompOFS_DCompleted;
        
        /// <remarks/>
        public event TabCompOFS_PCompletedEventHandler TabCompOFS_PCompleted;
        
        /// <remarks/>
        public event perRankDataCompletedEventHandler perRankDataCompleted;
        
        /// <remarks/>
        public event perRankData_DCompletedEventHandler perRankData_DCompleted;
        
        /// <remarks/>
        public event perRankData_PCompletedEventHandler perRankData_PCompleted;
        
        /// <remarks/>
        public event IntegralTableCompletedEventHandler IntegralTableCompleted;
        
        /// <remarks/>
        public event IntegralTable_dCompletedEventHandler IntegralTable_dCompleted;
        
        /// <remarks/>
        public event UserAchienementCompletedEventHandler UserAchienementCompleted;
        
        /// <remarks/>
        public event UserAchienement_dCompletedEventHandler UserAchienement_dCompleted;
        
        /// <remarks/>
        public event UserAchienement_pCompletedEventHandler UserAchienement_pCompleted;
        
        /// <remarks/>
        public event LottConCompletedEventHandler LottConCompleted;
        
        /// <remarks/>
        public event PeriodCompletedEventHandler PeriodCompleted;
        
        /// <remarks/>
        public event AllowCompletedEventHandler AllowCompleted;
        
        /// <remarks/>
        public event AllowTimeCompletedEventHandler AllowTimeCompleted;
        
        /// <remarks/>
        public event FlipCompletedEventHandler FlipCompleted;
        
        /// <remarks/>
        public event URLDecodeCompletedEventHandler URLDecodeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/addChall", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int addChall(string name, int lott, int issue, string num) {
            object[] results = this.Invoke("addChall", new object[] {
                        name,
                        lott,
                        issue,
                        num});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void addChallAsync(string name, int lott, int issue, string num) {
            this.addChallAsync(name, lott, issue, num, null);
        }
        
        /// <remarks/>
        public void addChallAsync(string name, int lott, int issue, string num, object userState) {
            if ((this.addChallOperationCompleted == null)) {
                this.addChallOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddChallOperationCompleted);
            }
            this.InvokeAsync("addChall", new object[] {
                        name,
                        lott,
                        issue,
                        num}, this.addChallOperationCompleted, userState);
        }
        
        private void OnaddChallOperationCompleted(object arg) {
            if ((this.addChallCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addChallCompleted(this, new addChallCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/logionUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int logionUser() {
            object[] results = this.Invoke("logionUser", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void logionUserAsync() {
            this.logionUserAsync(null);
        }
        
        /// <remarks/>
        public void logionUserAsync(object userState) {
            if ((this.logionUserOperationCompleted == null)) {
                this.logionUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlogionUserOperationCompleted);
            }
            this.InvokeAsync("logionUser", new object[0], this.logionUserOperationCompleted, userState);
        }
        
        private void OnlogionUserOperationCompleted(object arg) {
            if ((this.logionUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.logionUserCompleted(this, new logionUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ulogin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ulogin() {
            object[] results = this.Invoke("ulogin", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void uloginAsync() {
            this.uloginAsync(null);
        }
        
        /// <remarks/>
        public void uloginAsync(object userState) {
            if ((this.uloginOperationCompleted == null)) {
                this.uloginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnuloginOperationCompleted);
            }
            this.InvokeAsync("ulogin", new object[0], this.uloginOperationCompleted, userState);
        }
        
        private void OnuloginOperationCompleted(object arg) {
            if ((this.uloginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.uloginCompleted(this, new uloginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/perTableS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string perTableS(int num, string username, int issue) {
            object[] results = this.Invoke("perTableS", new object[] {
                        num,
                        username,
                        issue});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void perTableSAsync(int num, string username, int issue) {
            this.perTableSAsync(num, username, issue, null);
        }
        
        /// <remarks/>
        public void perTableSAsync(int num, string username, int issue, object userState) {
            if ((this.perTableSOperationCompleted == null)) {
                this.perTableSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnperTableSOperationCompleted);
            }
            this.InvokeAsync("perTableS", new object[] {
                        num,
                        username,
                        issue}, this.perTableSOperationCompleted, userState);
        }
        
        private void OnperTableSOperationCompleted(object arg) {
            if ((this.perTableSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.perTableSCompleted(this, new perTableSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/perTableD", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string perTableD(int num, string username, int issue) {
            object[] results = this.Invoke("perTableD", new object[] {
                        num,
                        username,
                        issue});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void perTableDAsync(int num, string username, int issue) {
            this.perTableDAsync(num, username, issue, null);
        }
        
        /// <remarks/>
        public void perTableDAsync(int num, string username, int issue, object userState) {
            if ((this.perTableDOperationCompleted == null)) {
                this.perTableDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnperTableDOperationCompleted);
            }
            this.InvokeAsync("perTableD", new object[] {
                        num,
                        username,
                        issue}, this.perTableDOperationCompleted, userState);
        }
        
        private void OnperTableDOperationCompleted(object arg) {
            if ((this.perTableDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.perTableDCompleted(this, new perTableDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/perTableP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string perTableP(int num, string username, int issue) {
            object[] results = this.Invoke("perTableP", new object[] {
                        num,
                        username,
                        issue});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void perTablePAsync(int num, string username, int issue) {
            this.perTablePAsync(num, username, issue, null);
        }
        
        /// <remarks/>
        public void perTablePAsync(int num, string username, int issue, object userState) {
            if ((this.perTablePOperationCompleted == null)) {
                this.perTablePOperationCompleted = new System.Threading.SendOrPostCallback(this.OnperTablePOperationCompleted);
            }
            this.InvokeAsync("perTableP", new object[] {
                        num,
                        username,
                        issue}, this.perTablePOperationCompleted, userState);
        }
        
        private void OnperTablePOperationCompleted(object arg) {
            if ((this.perTablePCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.perTablePCompleted(this, new perTablePCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TabCompOFS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TabCompOFS(int issNum) {
            object[] results = this.Invoke("TabCompOFS", new object[] {
                        issNum});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TabCompOFSAsync(int issNum) {
            this.TabCompOFSAsync(issNum, null);
        }
        
        /// <remarks/>
        public void TabCompOFSAsync(int issNum, object userState) {
            if ((this.TabCompOFSOperationCompleted == null)) {
                this.TabCompOFSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTabCompOFSOperationCompleted);
            }
            this.InvokeAsync("TabCompOFS", new object[] {
                        issNum}, this.TabCompOFSOperationCompleted, userState);
        }
        
        private void OnTabCompOFSOperationCompleted(object arg) {
            if ((this.TabCompOFSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TabCompOFSCompleted(this, new TabCompOFSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TabCompOFS_D", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TabCompOFS_D(int issNum) {
            object[] results = this.Invoke("TabCompOFS_D", new object[] {
                        issNum});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TabCompOFS_DAsync(int issNum) {
            this.TabCompOFS_DAsync(issNum, null);
        }
        
        /// <remarks/>
        public void TabCompOFS_DAsync(int issNum, object userState) {
            if ((this.TabCompOFS_DOperationCompleted == null)) {
                this.TabCompOFS_DOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTabCompOFS_DOperationCompleted);
            }
            this.InvokeAsync("TabCompOFS_D", new object[] {
                        issNum}, this.TabCompOFS_DOperationCompleted, userState);
        }
        
        private void OnTabCompOFS_DOperationCompleted(object arg) {
            if ((this.TabCompOFS_DCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TabCompOFS_DCompleted(this, new TabCompOFS_DCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TabCompOFS_P", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TabCompOFS_P(int issNum) {
            object[] results = this.Invoke("TabCompOFS_P", new object[] {
                        issNum});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TabCompOFS_PAsync(int issNum) {
            this.TabCompOFS_PAsync(issNum, null);
        }
        
        /// <remarks/>
        public void TabCompOFS_PAsync(int issNum, object userState) {
            if ((this.TabCompOFS_POperationCompleted == null)) {
                this.TabCompOFS_POperationCompleted = new System.Threading.SendOrPostCallback(this.OnTabCompOFS_POperationCompleted);
            }
            this.InvokeAsync("TabCompOFS_P", new object[] {
                        issNum}, this.TabCompOFS_POperationCompleted, userState);
        }
        
        private void OnTabCompOFS_POperationCompleted(object arg) {
            if ((this.TabCompOFS_PCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TabCompOFS_PCompleted(this, new TabCompOFS_PCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/perRankData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string perRankData() {
            object[] results = this.Invoke("perRankData", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void perRankDataAsync() {
            this.perRankDataAsync(null);
        }
        
        /// <remarks/>
        public void perRankDataAsync(object userState) {
            if ((this.perRankDataOperationCompleted == null)) {
                this.perRankDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnperRankDataOperationCompleted);
            }
            this.InvokeAsync("perRankData", new object[0], this.perRankDataOperationCompleted, userState);
        }
        
        private void OnperRankDataOperationCompleted(object arg) {
            if ((this.perRankDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.perRankDataCompleted(this, new perRankDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/perRankData_D", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string perRankData_D() {
            object[] results = this.Invoke("perRankData_D", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void perRankData_DAsync() {
            this.perRankData_DAsync(null);
        }
        
        /// <remarks/>
        public void perRankData_DAsync(object userState) {
            if ((this.perRankData_DOperationCompleted == null)) {
                this.perRankData_DOperationCompleted = new System.Threading.SendOrPostCallback(this.OnperRankData_DOperationCompleted);
            }
            this.InvokeAsync("perRankData_D", new object[0], this.perRankData_DOperationCompleted, userState);
        }
        
        private void OnperRankData_DOperationCompleted(object arg) {
            if ((this.perRankData_DCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.perRankData_DCompleted(this, new perRankData_DCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/perRankData_P", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string perRankData_P() {
            object[] results = this.Invoke("perRankData_P", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void perRankData_PAsync() {
            this.perRankData_PAsync(null);
        }
        
        /// <remarks/>
        public void perRankData_PAsync(object userState) {
            if ((this.perRankData_POperationCompleted == null)) {
                this.perRankData_POperationCompleted = new System.Threading.SendOrPostCallback(this.OnperRankData_POperationCompleted);
            }
            this.InvokeAsync("perRankData_P", new object[0], this.perRankData_POperationCompleted, userState);
        }
        
        private void OnperRankData_POperationCompleted(object arg) {
            if ((this.perRankData_PCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.perRankData_PCompleted(this, new perRankData_PCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IntegralTable", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string IntegralTable() {
            object[] results = this.Invoke("IntegralTable", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void IntegralTableAsync() {
            this.IntegralTableAsync(null);
        }
        
        /// <remarks/>
        public void IntegralTableAsync(object userState) {
            if ((this.IntegralTableOperationCompleted == null)) {
                this.IntegralTableOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIntegralTableOperationCompleted);
            }
            this.InvokeAsync("IntegralTable", new object[0], this.IntegralTableOperationCompleted, userState);
        }
        
        private void OnIntegralTableOperationCompleted(object arg) {
            if ((this.IntegralTableCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IntegralTableCompleted(this, new IntegralTableCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IntegralTable_d", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string IntegralTable_d() {
            object[] results = this.Invoke("IntegralTable_d", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void IntegralTable_dAsync() {
            this.IntegralTable_dAsync(null);
        }
        
        /// <remarks/>
        public void IntegralTable_dAsync(object userState) {
            if ((this.IntegralTable_dOperationCompleted == null)) {
                this.IntegralTable_dOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIntegralTable_dOperationCompleted);
            }
            this.InvokeAsync("IntegralTable_d", new object[0], this.IntegralTable_dOperationCompleted, userState);
        }
        
        private void OnIntegralTable_dOperationCompleted(object arg) {
            if ((this.IntegralTable_dCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IntegralTable_dCompleted(this, new IntegralTable_dCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UserAchienement", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UserAchienement(string userName, int issueNum) {
            object[] results = this.Invoke("UserAchienement", new object[] {
                        userName,
                        issueNum});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UserAchienementAsync(string userName, int issueNum) {
            this.UserAchienementAsync(userName, issueNum, null);
        }
        
        /// <remarks/>
        public void UserAchienementAsync(string userName, int issueNum, object userState) {
            if ((this.UserAchienementOperationCompleted == null)) {
                this.UserAchienementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserAchienementOperationCompleted);
            }
            this.InvokeAsync("UserAchienement", new object[] {
                        userName,
                        issueNum}, this.UserAchienementOperationCompleted, userState);
        }
        
        private void OnUserAchienementOperationCompleted(object arg) {
            if ((this.UserAchienementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserAchienementCompleted(this, new UserAchienementCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UserAchienement_d", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UserAchienement_d(string userName, int issueNum) {
            object[] results = this.Invoke("UserAchienement_d", new object[] {
                        userName,
                        issueNum});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UserAchienement_dAsync(string userName, int issueNum) {
            this.UserAchienement_dAsync(userName, issueNum, null);
        }
        
        /// <remarks/>
        public void UserAchienement_dAsync(string userName, int issueNum, object userState) {
            if ((this.UserAchienement_dOperationCompleted == null)) {
                this.UserAchienement_dOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserAchienement_dOperationCompleted);
            }
            this.InvokeAsync("UserAchienement_d", new object[] {
                        userName,
                        issueNum}, this.UserAchienement_dOperationCompleted, userState);
        }
        
        private void OnUserAchienement_dOperationCompleted(object arg) {
            if ((this.UserAchienement_dCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserAchienement_dCompleted(this, new UserAchienement_dCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UserAchienement_p", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UserAchienement_p(string userName, int issueNum) {
            object[] results = this.Invoke("UserAchienement_p", new object[] {
                        userName,
                        issueNum});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UserAchienement_pAsync(string userName, int issueNum) {
            this.UserAchienement_pAsync(userName, issueNum, null);
        }
        
        /// <remarks/>
        public void UserAchienement_pAsync(string userName, int issueNum, object userState) {
            if ((this.UserAchienement_pOperationCompleted == null)) {
                this.UserAchienement_pOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserAchienement_pOperationCompleted);
            }
            this.InvokeAsync("UserAchienement_p", new object[] {
                        userName,
                        issueNum}, this.UserAchienement_pOperationCompleted, userState);
        }
        
        private void OnUserAchienement_pOperationCompleted(object arg) {
            if ((this.UserAchienement_pCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserAchienement_pCompleted(this, new UserAchienement_pCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LottCon", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LottCon(string cond) {
            object[] results = this.Invoke("LottCon", new object[] {
                        cond});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LottConAsync(string cond) {
            this.LottConAsync(cond, null);
        }
        
        /// <remarks/>
        public void LottConAsync(string cond, object userState) {
            if ((this.LottConOperationCompleted == null)) {
                this.LottConOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLottConOperationCompleted);
            }
            this.InvokeAsync("LottCon", new object[] {
                        cond}, this.LottConOperationCompleted, userState);
        }
        
        private void OnLottConOperationCompleted(object arg) {
            if ((this.LottConCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LottConCompleted(this, new LottConCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Period", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Period(int lottID) {
            object[] results = this.Invoke("Period", new object[] {
                        lottID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PeriodAsync(int lottID) {
            this.PeriodAsync(lottID, null);
        }
        
        /// <remarks/>
        public void PeriodAsync(int lottID, object userState) {
            if ((this.PeriodOperationCompleted == null)) {
                this.PeriodOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPeriodOperationCompleted);
            }
            this.InvokeAsync("Period", new object[] {
                        lottID}, this.PeriodOperationCompleted, userState);
        }
        
        private void OnPeriodOperationCompleted(object arg) {
            if ((this.PeriodCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PeriodCompleted(this, new PeriodCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Allow", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Allow(string playName) {
            object[] results = this.Invoke("Allow", new object[] {
                        playName});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AllowAsync(string playName) {
            this.AllowAsync(playName, null);
        }
        
        /// <remarks/>
        public void AllowAsync(string playName, object userState) {
            if ((this.AllowOperationCompleted == null)) {
                this.AllowOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAllowOperationCompleted);
            }
            this.InvokeAsync("Allow", new object[] {
                        playName}, this.AllowOperationCompleted, userState);
        }
        
        private void OnAllowOperationCompleted(object arg) {
            if ((this.AllowCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AllowCompleted(this, new AllowCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AllowTime", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AllowTime(string playName) {
            object[] results = this.Invoke("AllowTime", new object[] {
                        playName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AllowTimeAsync(string playName) {
            this.AllowTimeAsync(playName, null);
        }
        
        /// <remarks/>
        public void AllowTimeAsync(string playName, object userState) {
            if ((this.AllowTimeOperationCompleted == null)) {
                this.AllowTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAllowTimeOperationCompleted);
            }
            this.InvokeAsync("AllowTime", new object[] {
                        playName}, this.AllowTimeOperationCompleted, userState);
        }
        
        private void OnAllowTimeOperationCompleted(object arg) {
            if ((this.AllowTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AllowTimeCompleted(this, new AllowTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Flip", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Flip(string lottN, int issue) {
            object[] results = this.Invoke("Flip", new object[] {
                        lottN,
                        issue});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FlipAsync(string lottN, int issue) {
            this.FlipAsync(lottN, issue, null);
        }
        
        /// <remarks/>
        public void FlipAsync(string lottN, int issue, object userState) {
            if ((this.FlipOperationCompleted == null)) {
                this.FlipOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFlipOperationCompleted);
            }
            this.InvokeAsync("Flip", new object[] {
                        lottN,
                        issue}, this.FlipOperationCompleted, userState);
        }
        
        private void OnFlipOperationCompleted(object arg) {
            if ((this.FlipCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FlipCompleted(this, new FlipCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/URLDecode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string URLDecode(string URLEncode) {
            object[] results = this.Invoke("URLDecode", new object[] {
                        URLEncode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void URLDecodeAsync(string URLEncode) {
            this.URLDecodeAsync(URLEncode, null);
        }
        
        /// <remarks/>
        public void URLDecodeAsync(string URLEncode, object userState) {
            if ((this.URLDecodeOperationCompleted == null)) {
                this.URLDecodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnURLDecodeOperationCompleted);
            }
            this.InvokeAsync("URLDecode", new object[] {
                        URLEncode}, this.URLDecodeOperationCompleted, userState);
        }
        
        private void OnURLDecodeOperationCompleted(object arg) {
            if ((this.URLDecodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.URLDecodeCompleted(this, new URLDecodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void addChallCompletedEventHandler(object sender, addChallCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addChallCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addChallCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void logionUserCompletedEventHandler(object sender, logionUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class logionUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal logionUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void uloginCompletedEventHandler(object sender, uloginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class uloginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal uloginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void perTableSCompletedEventHandler(object sender, perTableSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class perTableSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal perTableSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void perTableDCompletedEventHandler(object sender, perTableDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class perTableDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal perTableDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void perTablePCompletedEventHandler(object sender, perTablePCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class perTablePCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal perTablePCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void TabCompOFSCompletedEventHandler(object sender, TabCompOFSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TabCompOFSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TabCompOFSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void TabCompOFS_DCompletedEventHandler(object sender, TabCompOFS_DCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TabCompOFS_DCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TabCompOFS_DCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void TabCompOFS_PCompletedEventHandler(object sender, TabCompOFS_PCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TabCompOFS_PCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TabCompOFS_PCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void perRankDataCompletedEventHandler(object sender, perRankDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class perRankDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal perRankDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void perRankData_DCompletedEventHandler(object sender, perRankData_DCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class perRankData_DCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal perRankData_DCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void perRankData_PCompletedEventHandler(object sender, perRankData_PCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class perRankData_PCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal perRankData_PCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void IntegralTableCompletedEventHandler(object sender, IntegralTableCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IntegralTableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IntegralTableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void IntegralTable_dCompletedEventHandler(object sender, IntegralTable_dCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IntegralTable_dCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IntegralTable_dCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void UserAchienementCompletedEventHandler(object sender, UserAchienementCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserAchienementCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserAchienementCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void UserAchienement_dCompletedEventHandler(object sender, UserAchienement_dCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserAchienement_dCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserAchienement_dCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void UserAchienement_pCompletedEventHandler(object sender, UserAchienement_pCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserAchienement_pCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserAchienement_pCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void LottConCompletedEventHandler(object sender, LottConCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LottConCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LottConCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void PeriodCompletedEventHandler(object sender, PeriodCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PeriodCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PeriodCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void AllowCompletedEventHandler(object sender, AllowCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AllowCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AllowCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void AllowTimeCompletedEventHandler(object sender, AllowTimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AllowTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AllowTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void FlipCompletedEventHandler(object sender, FlipCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FlipCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FlipCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void URLDecodeCompletedEventHandler(object sender, URLDecodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class URLDecodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal URLDecodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591