//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace Pbzx.Web.NewPayCheck {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="gatewayOrderQuerySoapBinding", Namespace="http://www.99bill.com/gatewayapi/services/gatewayOrderQuery")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(GatewayOrderDetail))]
    public partial class GatewayOrderQueryService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback gatewayOrderQueryOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GatewayOrderQueryService() {
            this.Url = global::Pbzx.Web.Properties.Settings.Default.Pbzx_Web_NewPayCheck_GatewayOrderQueryService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event gatewayOrderQueryCompletedEventHandler gatewayOrderQueryCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://api.seashell.bill99.com", ResponseNamespace="http://www.99bill.com/gatewayapi/services/gatewayOrderQuery")]
        [return: System.Xml.Serialization.SoapElementAttribute("gatewayOrderQueryReturn")]
        public GatewayOrderQueryResponse gatewayOrderQuery(GatewayOrderQueryRequest request) {
            object[] results = this.Invoke("gatewayOrderQuery", new object[] {
                        request});
            return ((GatewayOrderQueryResponse)(results[0]));
        }
        
        /// <remarks/>
        public void gatewayOrderQueryAsync(GatewayOrderQueryRequest request) {
            this.gatewayOrderQueryAsync(request, null);
        }
        
        /// <remarks/>
        public void gatewayOrderQueryAsync(GatewayOrderQueryRequest request, object userState) {
            if ((this.gatewayOrderQueryOperationCompleted == null)) {
                this.gatewayOrderQueryOperationCompleted = new System.Threading.SendOrPostCallback(this.OngatewayOrderQueryOperationCompleted);
            }
            this.InvokeAsync("gatewayOrderQuery", new object[] {
                        request}, this.gatewayOrderQueryOperationCompleted, userState);
        }
        
        private void OngatewayOrderQueryOperationCompleted(object arg) {
            if ((this.gatewayOrderQueryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.gatewayOrderQueryCompleted(this, new gatewayOrderQueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://gatewayquery.dto.domain.seashell.bill99.com")]
    public partial class GatewayOrderQueryRequest {
        
        private string endTimeField;
        
        private string inputCharsetField;
        
        private string merchantAcctIdField;
        
        private string orderIdField;
        
        private int queryModeField;
        
        private int queryTypeField;
        
        private string requestPageField;
        
        private string signMsgField;
        
        private int signTypeField;
        
        private string startTimeField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string endTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string inputCharset {
            get {
                return this.inputCharsetField;
            }
            set {
                this.inputCharsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string merchantAcctId {
            get {
                return this.merchantAcctIdField;
            }
            set {
                this.merchantAcctIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string orderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
            }
        }
        
        /// <remarks/>
        public int queryMode {
            get {
                return this.queryModeField;
            }
            set {
                this.queryModeField = value;
            }
        }
        
        /// <remarks/>
        public int queryType {
            get {
                return this.queryTypeField;
            }
            set {
                this.queryTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string requestPage {
            get {
                return this.requestPageField;
            }
            set {
                this.requestPageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string signMsg {
            get {
                return this.signMsgField;
            }
            set {
                this.signMsgField = value;
            }
        }
        
        /// <remarks/>
        public int signType {
            get {
                return this.signTypeField;
            }
            set {
                this.signTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string startTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://gatewayquery.dto.domain.seashell.bill99.com")]
    public partial class GatewayOrderDetail {
        
        private string dealIdField;
        
        private string dealTimeField;
        
        private long feeField;
        
        private long orderAmountField;
        
        private string orderIdField;
        
        private string orderTimeField;
        
        private long payAmountField;
        
        private string payResultField;
        
        private string payTypeField;
        
        private string signInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dealId {
            get {
                return this.dealIdField;
            }
            set {
                this.dealIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dealTime {
            get {
                return this.dealTimeField;
            }
            set {
                this.dealTimeField = value;
            }
        }
        
        /// <remarks/>
        public long fee {
            get {
                return this.feeField;
            }
            set {
                this.feeField = value;
            }
        }
        
        /// <remarks/>
        public long orderAmount {
            get {
                return this.orderAmountField;
            }
            set {
                this.orderAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string orderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string orderTime {
            get {
                return this.orderTimeField;
            }
            set {
                this.orderTimeField = value;
            }
        }
        
        /// <remarks/>
        public long payAmount {
            get {
                return this.payAmountField;
            }
            set {
                this.payAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string payResult {
            get {
                return this.payResultField;
            }
            set {
                this.payResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string payType {
            get {
                return this.payTypeField;
            }
            set {
                this.payTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string signInfo {
            get {
                return this.signInfoField;
            }
            set {
                this.signInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://gatewayquery.dto.domain.seashell.bill99.com")]
    public partial class GatewayOrderQueryResponse {
        
        private string currentPageField;
        
        private string errCodeField;
        
        private string merchantAcctIdField;
        
        private GatewayOrderDetail[] ordersField;
        
        private string pageCountField;
        
        private string pageSizeField;
        
        private string recordCountField;
        
        private string signMsgField;
        
        private int signTypeField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string currentPage {
            get {
                return this.currentPageField;
            }
            set {
                this.currentPageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string errCode {
            get {
                return this.errCodeField;
            }
            set {
                this.errCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string merchantAcctId {
            get {
                return this.merchantAcctIdField;
            }
            set {
                this.merchantAcctIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public GatewayOrderDetail[] orders {
            get {
                return this.ordersField;
            }
            set {
                this.ordersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string pageCount {
            get {
                return this.pageCountField;
            }
            set {
                this.pageCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string pageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string recordCount {
            get {
                return this.recordCountField;
            }
            set {
                this.recordCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string signMsg {
            get {
                return this.signMsgField;
            }
            set {
                this.signMsgField = value;
            }
        }
        
        /// <remarks/>
        public int signType {
            get {
                return this.signTypeField;
            }
            set {
                this.signTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void gatewayOrderQueryCompletedEventHandler(object sender, gatewayOrderQueryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class gatewayOrderQueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal gatewayOrderQueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GatewayOrderQueryResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GatewayOrderQueryResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591